### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [punkave/jquery-rest-admin#6]
Hello, under what license is this project released under ? Thank-you.

**Comment by boutell** [comment]
Hi @suprafun, I confess I was stunned to see your message — you're the first to inquire on this repo which I last worked on perhaps 8 years ago 😄 

I would tend to suggest you use something newer and that is actively maintained.

But, it is released under the MIT license. Copyright 2012 P'unk Avenue LLC.
